# Book settings
# Learn more at https://jupyterbook.org/customize/config.html

title: CA4015 Assignment 1
author: Kian Sweeney
copyright: "2021"
logo: dcu-logo.png
only_build_toc_files: true

# Force re-execution of notebooks on each build.
# See https://jupyterbook.org/content/execute.html
execute:
  execute_notebooks: force
  stderr_output: remove  # One of 'show', 'remove', 'remove-warn', 'warn', 'error', 'severe'

# Define the name of the latex output file for PDF builds
latex:
  latex_documents:
    targetname: assignment1_ks.tex

# Add a bibtex file so that we can create citations
bibtex_bibfiles:
  - references.bib

# Information about where the book exists on the web
repository:
  url: https://github.com/kiansweeney11/ca4015-assignment-1  # Online location of your book
#  path_to_book: docs  # Optional path to your book, relative to the repository root
  branch: master  # Which branch of the repository should be used when creating links (optional)

# Add GitHub buttons to your book
# See https://jupyterbook.org/customize/config.html#add-a-link-to-your-repository
html:
  use_issues_button: true
  use_repository_button: true
  baseurl: "https://kiansweeney11.github.io/ca4015-assignment-1/introduction.html"  # The base URL where your book will be hosted.
